import pyautogui as py
import time as t
t.sleep(0.5)
py.press('winleft')
t.sleep(0.5)
py.write('chrome', interval=0.05)
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.hotkey('ctrl', 'shift', 'n')
py.write('https://mail.google.com/mail/u/0/#inbox', interval=0.01)
py.press('enter')
t.sleep(10.0)
py.write('digite seu email', interval=0.01)
t.sleep(0.5)
py.press('enter')
t.sleep(10.0)
py.write('digite sua senha')
t.sleep(0.5)
py.press('Enter')
t.sleep(6.0)
py.moveTo(127,279)
t.sleep(6.0)
py.click()